
# note that: after changing this you need to reboot the app on streamlit

# number of images to generate (use 4 when using multiple GPUs)
N_IMAGES = 2

# see VAST instance details and copy paste public url that corresponds to the port 8000
SERVER0 = "<url>:<port>"

AWS_ACCESS_KEY=
AWS_SECRET_KEY=
REGION_NAME='ap-southeast-1'

REPLICATE_API_TOKEN=
